.DEFAULT_GOAL := help

.PHONY: help clean docs requirements ci_requirements dev_requirements \
        prod_requirements validation_requirements doc_requirements shell \
        test coverage isort_check isort style lint quality validate \
        html_coverage upgrade

# For opening files in a browser. Use like: $(BROWSER)relative/path/to/file.html
BROWSER := python -m webbrowser file://$(CURDIR)/

# Generates a help message. Borrowed from https://github.com/pydanny/cookiecutter-djangopackage.
help: ## display this help message
	@echo "Please use \`make <target>\` where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

clean: ## delete generated byte code and coverage reports
	find . -name '*.pyc' -delete
	coverage erase
	rm -rf assets

docs: ## generate Sphinx HTML documentation, including API docs
	uv run doc8 --ignore-path docs/_build README.rst docs
	make -e -C docs clean
	make -e -C docs html
	$(BROWSER)docs/_build/html/index.html

requirements: ## install development environment requirements
	uv sync --group dev

ci_requirements: ## sync to requirements needed for CI checks
	uv sync --group quality

dev_requirements: ## sync to requirements for local development
	uv sync --group dev

prod_requirements: ## sync virtualenv to requirements needed for production
	uv sync

validation_requirements: ## sync to requirements for testing & code quality checking
	uv sync --group quality

doc_requirements: ## sync to requirements for documentation
	uv sync --group doc

shell: ## run Django shell
	python manage.py shell

test: clean ## run tests and generate coverage report
	uv run pytest

# To be run from CI context
coverage: clean
	uv run pytest --cov-report html
	$(BROWSER)htmlcov/index.html

isort_check: ## check that isort has been run
	uv run isort --check-only codejail_service/

isort: ## run isort to sort imports in all Python files
	uv run isort --atomic codejail_service/

style: ## run Python style checker
	uv run pylint --rcfile=pylintrc codejail_service manage.py

lint: ## run Python code linting
	uv run pylint --rcfile=pylintrc codejail_service manage.py

quality: ## run all quality checks
	uv run pylint codejail_service test_utils manage.py api_tests
	uv run pycodestyle codejail_service manage.py api_tests
	uv run pydocstyle codejail_service manage.py api_tests
	uv run isort --check-only --diff test_utils codejail_service manage.py api_tests
	make selfcheck

validate: test quality ## run tests, quality

html_coverage: ## generate and view HTML coverage report
	coverage html && open htmlcov/index.html

upgrade: ## update python dependencies
	uv run --with edx-lint edx_lint write_uv_constraints pyproject.toml
	uv lock --upgrade

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."
